Some weights of the model checkpoint at roberta-base were not used when initializing RobertaForSequenceClassification: ['lm_head.decoder.weight', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'roberta.pooler.dense.weight', 'lm_head.dense.bias', 'lm_head.bias', 'lm_head.layer_norm.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Epoch:   0%|                                            | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "src/models/train_model.py", line 44, in <module>
    for step, batch in enumerate(train_dataloader):
  File "/zhome/22/4/118839/Ml_Ops_Project/Venv/lib64/python3.6/site-packages/torch/utils/data/dataloader.py", line 348, in __iter__
    if self.persistent_workers and self.num_workers > 0:
AttributeError: 'DataLoader' object has no attribute 'persistent_workers'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/Ml_Ops_Project/src/models/train_model.py in <module>
     42   model.zero_grad()
     43
---> 44   for step, batch in enumerate(train_dataloader):
     45
     46       input_ids = batch[0].to(device)
~/Ml_Ops_Project/Venv/lib64/python3.6/site-packages/torch/utils/data/dataloader.py in __iter__(self)
    346         # the iterator is only created once in the lifetime of the
    347         # DataLoader object so that workers can be reused
--> 348         if self.persistent_workers and self.num_workers > 0:
    349             if self._iterator is None:
    350                 self._iterator = self._get_iterator()
AttributeError: 'DataLoader' object has no attribute 'persistent_workers'